class Tensor:
    """N-dimensional tensor backed by C memory."""

    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def size(self) -> int: ...
    def __init__(self, shape: list[int]) -> None: ...
    @staticmethod
    def from_bytes(data: bytes, shape: list[int]) -> Tensor: ...
    @staticmethod
    def from_list(data: list[float], shape: list[int]) -> Tensor: ...
    @staticmethod
    def ones_like(other: Tensor) -> Tensor: ...
    def to_bytes(self) -> bytes: ...
    def to_list(self) -> list[float]: ...
    def __getitem__(self, idx: int | tuple[int, ...]) -> float: ...
    def __setitem__(self, idx: int | tuple[int, ...], value: float) -> None: ...
    def __len__(self) -> int: ...
    def add(self, other: Tensor) -> Tensor: ...
    def subtract(self, other: Tensor) -> Tensor: ...
    def elementwise_mul(self, other: Tensor) -> Tensor: ...
    def matmul(self, other: Tensor) -> Tensor: ...
    def relu(self) -> Tensor: ...
    def transpose2d(self) -> Tensor: ...
    def scale(self, scalar: float) -> Tensor: ...
    def clone(self) -> Tensor: ...
    def fill(self, value: float) -> None: ...
    def sum(self) -> float: ...
    def argmax(self) -> int: ...
    def relu_backward(self, relu_output: Tensor) -> Tensor: ...
    def softmax_cross_entropy(self, target: Tensor) -> float: ...
    def softmax_cross_entropy_backward(self, target: Tensor) -> Tensor: ...
