"""Type stubs for _nn_core C extension. Update as you implement bindings."""

class Tensor:
    """N-dimensional tensor backed by C memory."""

    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def size(self) -> int: ...
    def __init__(self, shape: list[int]) -> None: ...
    @staticmethod
    def from_bytes(data: bytes, shape: list[int]) -> Tensor: ...
    @staticmethod
    def from_list(data: list[float], shape: list[int]) -> Tensor: ...
    def to_bytes(self) -> bytes: ...
    def to_list(self) -> list[float]: ...
    def __getitem__(self, idx: int | tuple[int, ...]) -> float: ...
    def __setitem__(self, idx: int | tuple[int, ...], value: float) -> None: ...

# Add more stubs here as you implement bindings:
# class Layer: ...
# class NeuralNet: ...
# class GPUTensor: ...
